spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crypto_currency?ApplicationName=TestSweetApp
    username: postgres
    password: postgres

coin_url : https://api.coinlore.net/api/ticker/?id=